// 7-React/shop-it-v1/src/App.js
import React from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import Navbar from './components/Navbar';
import Item from './components/Item';

class App extends React.Component {
  state = {
    items: [
      {
        id: 1,
        name: 'Laptop',
        price: 198000,
        canBuy: true,
        imgPath: 'images/Laptop.png',
        description: 'new mac pro'
      },
      {
        id: 2,
        name: 'Mobile',
        price: 43000,
        canBuy: true,
        imgPath: 'images/Mobile.png',
        description: 'new  pro'
      }
    ]
  }

  renderItems() {
    let { items } = this.state;
    return items.map((item, idx) => {
      return (
        <div className="list-group-item" key={idx}>
          <Item value={item} />
        </div>
      )
    })
  }
  render() {
    return (
      <div>
        <Navbar title="shopIT" />
        <hr />
        <hr />
        <div className="container">
          {this.renderItems()}
        </div>
      </div>
    );
  }
}

export default App;

// 6-NG/3-eat-IT-v2/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'eat-IT-v1';
  items = [
    {
      id: 1,
      name: 'Veg',
      price: 200.00,
      canBuy: true,
      imgPath: `assets/${'veg.png'}`,
      description: 'veg is always yummy'
    },
    {
      id: 2,
      name: 'Non Veg',
      price: 150.00,
      canBuy: true,
      imgPath: "assets/non-veg.png",
      description: 'non-veg is yummy'
    },

  ]


}

<div>

  <app-navbar [value]="title"></app-navbar>

  <hr />
  <hr />

  <div class="container">
    <div class="list-group-item" *ngFor="let item of items">
      <app-item [value]="item"></app-item>
    </div>
  </div>


</div>
