// 6-NG/4-eat-IT-v4 ( services ) /src/app/item/item.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.css']
})
export class ItemComponent implements OnInit {

  @Input("value") item;
  @Input("cartQty") cartQty;
  @Output() buy = new EventEmitter();
  currentTab = 1
  reviews = [
    { author: 'who@mail.com', stars: 5, body: 'sample-review-1' },
    { author: 'who@mail.com', stars: 2, body: 'sample-review-2' }
  ]

  // private cartService: CartService;
  // constructor(cartService: CartService) {
  //   this.cartService = cartService;
  // }
  // or
  constructor(private cartService: CartService) { }

  ngOnInit() {
  }

  handleBuy(event) {
    //this.buy.emit({ item: this.item })
    this.cartService.addToCart(this.item,1)
  }

  isTabSelected(tabIndex) {
    return this.currentTab === tabIndex;
  }
  changeTab(event, tabIndex) {
    event.preventDefault();
    this.currentTab = tabIndex;
  }

}

<div class="row">
  <div class="col-3 col-sm-3 col-md-3 col-lg-3">
    <img [src]="item.imgPath" class="img-fluid" />
  </div>
  <div class="col-9 col-sm-9 col-md-9 col-lg-9">
    <h5>{{item.name|uppercase}} - <!--<small>{{item.date|date:'hh:MM'}}</small>--></h5>
    <h6>{{item.price|priceDiscount:item.discount|currency:item.currency:'symbol'}}</h6>
    <button (click)="handleBuy($event)" *ngIf="item.canBuy" class="btn btn-sm btn-dark">buy</button>
    &nbsp;<input size="2" readonly [value]="cartQty" />
    <br />
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a (click)="changeTab($event,1)" class="nav-link" [class.active]="isTabSelected(1)" href="/">Description
        </a>
      </li>
      <li class="nav-item">
        <a (click)="changeTab($event,2)" [ngClass]="{'nav-link':true,active:isTabSelected(2)}" href="/">Ingre..
        </a>
      </li>
      <li class="nav-item">
        <a (click)="changeTab($event,3)" [ngClass]="{'nav-link':true,active:isTabSelected(3)}" href="/">Reviews
        </a>
      </li>
    </ul>
    <div *ngIf="isTabSelected(1)">{{item.description | slice:0:1000}}</div>
    <div *ngIf="isTabSelected(2)">Not Yet</div>
    <div *ngIf="isTabSelected(3)">
      <div *ngFor="let review of reviews">
        <app-review [value]="review">
        </app-review>
      </div>
    </div>
  </div>
</div>
<pre>
  <!-- {{item|json}} -->
</pre>

// 7-React/shop-it-v1/src/components/Item.js
import React, { Component } from 'react';
import classNames from 'classnames'


class Item extends Component {
    state = {
        currentTab: 1,
    }
    changeTab(tabIndex) {
        this.setState({ currentTab: tabIndex }) // re-render
    }
    renderBuyBtn(item) {
        if (item.canBuy) return <button className="btn btn-sm btn-dark">buy</button>
    }
    renderTabPanel(item) {
        let { currentTab } = this.state;
        switch (currentTab) {
            case 1: return (<div>{item.description}</div>)
            case 2: return (<div>Not Yet</div>)
            case 3: return (<div>None Yet</div>)
            default: return null;
        }
    }
    render() {
        let { value: item } = this.props;
        let { currentTab } = this.state;
        return (
            <div>
                <div className="row">
                    <div className="col-3 col-sm-3 col-md-3">
                        <img src={item.imgPath} className="img-fluid" />
                    </div>
                    <div className="col-9 col-sm-9 col-md-9">
                        <h5>{item.name}</h5>
                        <h6>&#8377;{item.price}</h6>
                        {this.renderBuyBtn(item)}
                        <ul className="nav nav-tabs">
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(1)} className={classNames('nav-link', { active: currentTab === 1 })} href="#">Reviews</a>
                            </li>
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(2)} className={classNames('nav-link', { active: currentTab === 2 })} href="#">Specifcation</a>
                            </li>
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(3)} className={classNames('nav-link', { active: currentTab === 3 })} href="#">Reviews</a>
                            </li>
                        </ul>
                        {this.renderTabPanel(item)}
                    </div>
                </div>
            </div>
        );
    }
}

export default Item;
