// 6-NG/3-eat-IT-v2/src/app/item/item.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.css']
})
export class ItemComponent implements OnInit {

  @Input("value") item;
  currentTab = 1
  reviews = [
    { author: 'who@mail.com', stars: 5, body: 'sample-review-1' },
    { author: 'who@mail.com', stars: 2, body: 'sample-review-2' }
  ]


  ngOnInit() {
  }

  isTabSelected(tabIndex) {
    return this.currentTab === tabIndex;
  }
  changeTab(event, tabIndex) {
    event.preventDefault();
    this.currentTab = tabIndex;
  }

}

<div class="row">
  <div class="col-3 col-sm-3 col-md-3 col-lg-3">
    <img [src]="item.imgPath" class="img-fluid" />
  </div>
  <div class="col-9 col-sm-9 col-md-9 col-lg-9">
    <h5>{{item.name}}</h5>
    <h6>{{item.price}}</h6>
    <button *ngIf="item.canBuy" class="btn btn-sm btn-dark">buy</button>
    <br />
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a (click)="changeTab($event,1)" class="nav-link" [class.active]="isTabSelected(1)" href="/">Description
        </a>
      </li>
      <li class="nav-item">
        <a (click)="changeTab($event,2)" [ngClass]="{'nav-link':true,active:isTabSelected(2)}" href="/">Ingre..
        </a>
      </li>
      <li class="nav-item">
        <a (click)="changeTab($event,3)" [ngClass]="{'nav-link':true,active:isTabSelected(3)}" href="/">Reviews
        </a>
      </li>
    </ul>
    <div *ngIf="isTabSelected(1)">{{item.description}}</div>
    <div *ngIf="isTabSelected(2)">Not Yet</div>
    <div *ngIf="isTabSelected(3)">
      <div *ngFor="let review of reviews">
        <app-review [value]="review">
        </app-review>
      </div>
    </div>
  </div>
</div>

// 7-React/eat-it-v1/src/components/Item.js
import React, { Component } from 'react';
import classNames from 'classnames'
import Review from './Review'
import axios from 'axios';

class Item extends Component {
    state = {
        currentTab: 1,
        reviews: []
    }
    changeTab(e, tabIndex) {
        e.preventDefault();
        this.setState({ currentTab: tabIndex }, () => {
            if (tabIndex === 3) {
                let { value: item } = this.props;
                let api = `http://localhost:8081/api/v1/items/${item.id}/reviews`;
                axios.get(api)
                    .then(response => response.data)
                    .then(reviews => {
                        this.setState({ reviews })
                    })
            }
        }) // re-render
    } 
    handleBuy(e) {
        let { onBuy, value: item } = this.props;
        if (onBuy)
            onBuy({ item, qty: 1 })
    }
    renderBuyBtn(item) {
        if (true) return <button onClick={e => this.handleBuy(e)} className="btn btn-sm btn-dark">buy</button>
    }
    renderReviews() {
        let { reviews } = this.state;
        return reviews.map((review, idx) => {
            return <Review value={review} key={idx} />
        })
    }
    renderTabPanel(item) {
        let { currentTab } = this.state;
        switch (currentTab) {
            case 1: return (<div>{item.description}</div>)
            case 2: return (<div>Not Yet</div>)
            case 3: return (<div>{this.renderReviews()}</div>)
            default: return null;
        }
    }
    render() {
        let { value: item } = this.props;
        let { currentTab } = this.state;
        return (
            <div>
                <div className="row">
                    <div className="col-3 col-sm-3 col-md-3">
                        <img src={item.imgPath} alt={item.name} className="img-fluid" />
                    </div>
                    <div className="col-9 col-sm-9 col-md-9">
                        <h5>{item.name}</h5>
                        <h6>&#8377;{item.price}</h6>
                        {this.renderBuyBtn(item)}
                        <ul className="nav nav-tabs">
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(e, 1)} className={classNames('nav-link', { active: currentTab === 1 })} href="/">Reviews</a>
                            </li>
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(e, 2)} className={classNames('nav-link', { active: currentTab === 2 })} href="/">Specifcation</a>
                            </li>
                            <li className="nav-item">
                                <a onClick={e => this.changeTab(e, 3)} className={classNames('nav-link', { active: currentTab === 3 })} href="/">Reviews</a>
                            </li>
                        </ul>
                        {this.renderTabPanel(item)}
                    </div>
                </div>
            </div>
        );
    }
}

export default Item;
