// 6-NG/3-eat-IT-v2/src/app/review/review.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-review',
  templateUrl: './review.component.html',
  styleUrls: ['./review.component.css']
})
export class ReviewComponent implements OnInit {

  @Input("value") review;

  stars = [];

  constructor() { }

  ngOnInit() {
  }

  ngDoCheck() {
    this.stars = []
    for (let i = 0; i < this.review.stars; i++)
      this.stars.push(i)
  }

}

<div class="alert alert-info">
  <span>
    <i *ngFor="let n of stars" 
           style="font-size: 20px;color: red;" 
           class="fa fa-star">
    </i>
  </span>
  &mdash;<span>{{review.author}}</span>
  <hr />
  <div>{{review.body}}</div>
</div>

// 7-React/eat-it-v1/src/components/Review.js
import React from 'react';


function renderStars(n) {
    let arr = [];
    for (let i = 0; i < n; i++)
        arr.push(<i key={i} className="fa fa-star" style={{ color: 'orange' }}></i>)
    return arr;
}

function Review(props) {
    let { value: review } = props;
    return (
        <div className="alert alert-danger">
            {renderStars(review.stars)} &mdash; {review.author}
            <hr />
            <div>{review.body}</div>
        </div>
    );
}

export default Review;
