// 7-React/eat-it-v1/src/App.js
import React from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
import Navbar from './components/Navbar';
import CartView from './components/CartView'
import Home from './components/Home'
import { BrowserRouter as Router, Route, Link } from 'react-router-dom'
import ItemList from './components/ItemList';

class App extends React.Component {
  state = {
    cart: [],
  }
  addToCart(item, qty) {
    let { cart } = this.state;
    cart = cart.concat(item);
    this.setState({ cart })
  }
  render() {
    let { cart } = this.state;
    return (
      <div>
        <Navbar title="eat-IT" />
        <Router>
          <div>
            <hr />
            <i className="fa fa-shopping-cart"></i>&nbsp;
            {cart.length} items in cart
            <hr />
            <ul className="nav nav-pills">
              <li className="nav-item">
                <Link className="nav-link" to="/">Home</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/items">Items</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/cart">Cart</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link disabled" to="/orders">Orders</Link>
              </li>
            </ul>
            <hr />
            <div className="container">
              <div>
                <Route path={"/"} exact={true} component={Home} />
                <Route path={"/items"} render={() => <ItemList onBuy={e => this.addToCart(e.item)} />} />
                <Route path={"/cart"} render={() => <CartView value={cart} />} />
              </div>
            </div>
          </div>
        </Router>
      </div>
    );
  }
}

export default App;

// 6-NG/3-eat-IT-v3 ( routing )/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  title = 'eat-IT-v1';
  cart = {}
  cartQty = 0;

  addToCart(event) {
    let { item } = event;
    let { id } = item;
    let itemLine = this.cart[id];
    if (itemLine) {
      itemLine = { item, qty: itemLine.qty + 1 }
    } else {
      itemLine = { item, qty: 1 }
    }
    this.cart = { ...this.cart, [id]: itemLine }
    this.cartQty = Object.keys(this.cart).length;
  }



}

<div>
  <app-navbar [value]="title"></app-navbar>
  <hr />
  <app-cart-badge [value]="cartQty"></app-cart-badge>
  <hr />
  <div class="container">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link " href="/">home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " routerLink="/items">items</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " routerLink="/cart">cart</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " routerLink="/orders">orders</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " routerLink="/login">sign-in</a>
      </li>
    </ul>
  </div>
  <hr />
  
  <div class="container">
    <router-outlet></router-outlet>
  </div>

</div>
